<?php

/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

namespace Google\Service\Walletobjects;

/**
 * Indicates that the issuer would like Google Wallet to send expiry
 * notifications 2 days prior to the card expiration.
 *
 * NOTE: This file is auto generated by `google-apis-client-generator`, DO NOT EDIT!
 *
 * @phpcs:disable Generic.NamingConventions.UpperCaseConstantName
 */
class ExpiryNotification extends \Google\Model
{
    /**
     * Indicates if the object needs to have expiry notification enabled.
     */
    public bool $enableNotification;

    /**
     * Indicates if the object needs to have expiry notification enabled.
     *
     * @param bool $enableNotification
     */
    public function setEnableNotification($enableNotification)
    {
        $this->enableNotification = $enableNotification;
    }
    /**
     * @return bool
     */
    public function getEnableNotification()
    {
        return $this->enableNotification;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
// phpcs:disable PSR1.Files.SideEffects.FoundWithSymbols
class_alias(ExpiryNotification::class, 'Google_Service_Walletobjects_ExpiryNotification');
