<?php

/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

namespace Google\Service\Walletobjects;

/**
 * NOTE: This file is auto generated by `google-apis-client-generator`, DO NOT EDIT!
 *
 * @phpcs:disable Generic.NamingConventions.UpperCaseConstantName
 */
class ImageUri extends \Google\Model
{
    /**
     * Additional information about the image, which is unused and retained only
     * for backward compatibility.
     * @deprecated
     */
    public string $description;
    protected $localizedDescriptionType = LocalizedString::class;
    protected $localizedDescriptionDataType = '';
    /**
     * The location of the image. URIs must have a scheme.
     */
    public string $uri;

    /**
     * Additional information about the image, which is unused and retained only
     * for backward compatibility.
     *
     * @param string $description
     * @deprecated
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }
    /**
     * @return string
     * @deprecated
     */
    public function getDescription()
    {
        return $this->description;
    }
    /**
     * Translated strings for the description, which are unused and retained only
     * for backward compatibility.
     *
     * @param LocalizedString $localizedDescription
     * @deprecated
     */
    public function setLocalizedDescription(LocalizedString $localizedDescription)
    {
        $this->localizedDescription = $localizedDescription;
    }
    /**
     * @return LocalizedString
     * @deprecated
     */
    public function getLocalizedDescription()
    {
        return $this->localizedDescription;
    }
    /**
     * The location of the image. URIs must have a scheme.
     *
     * @param string $uri
     */
    public function setUri($uri)
    {
        $this->uri = $uri;
    }
    /**
     * @return string
     */
    public function getUri()
    {
        return $this->uri;
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
// phpcs:disable PSR1.Files.SideEffects.FoundWithSymbols
class_alias(ImageUri::class, 'Google_Service_Walletobjects_ImageUri');
